# .github/workflows/test-version-alert.yml
name: 🤖 Test Version.ts Slack Alert

on:
  workflow_dispatch

jobs:
  post-version:
    runs-on: ubuntu-latest
    steps:
      # 1) Grab the repo
      - uses: actions/checkout@v3

      # 2) Read version.ts into an output variable
      - name: Read version.ts
        id: read_version
        run: |
          echo "file_content<<EOF" >> $GITHUB_OUTPUT
          sed -e 's/```/` ` `/g' packages/analytics-browser/src/version.ts >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 3) Read amplitude-snippet.js into another output variable
      - name: Read amplitude-snippet.js
        id: read_snippet
        run: |
          echo "snippet_content<<EOF" >> $GITHUB_OUTPUT
          sed -e 's/```/` ` `/g' packages/analytics-browser/generated/amplitude-snippet.js >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 4) Send Slack message with both files included
      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: custom
          custom_payload: |
            {
              "text": ":package: *version.ts* contents (manual test):\n" +
                      "```${{ steps.read_version.outputs.file_content }}```\n\n" +
                      ":bookmark_tabs: *Updated Snippet (amplitude-snippet.js):*\n" +
                      "```${{ steps.read_snippet.outputs.snippet_content }}```"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
