name: 🤖 Test Version.ts Slack Alert

on:
  workflow_dispatch

jobs:
  post-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Read version.ts into temp file
      - name: Read version.ts
        id: read_version
        run: |
          sed -e 's/```/` ` `/g' packages/analytics-browser/src/version.ts > version.txt
          echo "file_content<<EOF" >> $GITHUB_OUTPUT
          cat version.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # Read amplitude-snippet.js into temp file
      - name: Read amplitude-snippet.js
        id: read_snippet
        run: |
          sed -e 's/```/` ` `/g' packages/analytics-browser/generated/amplitude-snippet.js > snippet.txt
          echo "snippet_content<<EOF" >> $GITHUB_OUTPUT
          cat snippet.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # Send Slack notification
      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: custom
          custom_payload: |
            {
              "text": ":package: *version.ts* contents (manual test):\n" +
                      "```${{ steps.read_version.outputs.file_content }}```\n\n" +
                      ":bookmark_tabs: *Updated Snippet (amplitude-snippet.js):*\n" +
                      "```${{ steps.read_snippet.outputs.snippet_content }}```"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
