name: 🤖 Test Version.ts Slack Alert

on:
  workflow_dispatch

jobs:
  post-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read version.ts
        id: read_version
        run: |
          content=$(sed -e 's/```/` ` `/g' packages/analytics-browser/src/version.ts | base64 -w0)
          echo "file_content=$content" >> $GITHUB_OUTPUT

      - name: Read amplitude-snippet.js
        id: read_snippet
        run: |
          content=$(sed -e 's/```/` ` `/g' packages/analytics-browser/generated/amplitude-snippet.js | base64 -w0)
          echo "snippet_content=$content" >> $GITHUB_OUTPUT

      # Send Slack notification
      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: custom
          custom_payload: |
            {
              "text": ":package: *version.ts* (base64 decoded):\n" +
                      "```${{ steps.read_version.outputs.file_content }}```\n\n" +
                      ":bookmark_tabs: *Snippet (base64):*\n" +
                      "```${{ steps.read_snippet.outputs.snippet_content }}```"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
